package io.github.sinri.keel.core.json;

import io.vertx.core.buffer.Buffer;
import io.vertx.core.json.JsonObject;
import io.vertx.core.shareddata.Shareable;

import javax.annotation.Nonnull;


/**
 * An interface representing an unmodifiable entity that can be converted to a JSON object.
 * This interface extends {@link Iterable} and {@link Shareable}, providing methods to read various types of values from
 * the underlying JSON structure.
 *
 * @since 3.0.0
 */
public interface UnmodifiableJsonifiableEntity
        extends JsonObjectReadable, JsonSerializable, Shareable {
    static UnmodifiableJsonifiableEntity wrap(@Nonnull JsonObject jsonObject) {
        return new UnmodifiableJsonifiableEntityImpl(jsonObject);
    }

    /**
     * @return A JSON Object composed by the string generated by
     *         `io.github.sinri.keel.core.json.UnmodifiableJsonifiableEntity#toJsonExpression()`.
     * @since 3.2.17
     */
    @Nonnull
    default JsonObject cloneAsJsonObject() {
        return new JsonObject(toJsonExpression());
    }

    /**
     * As of 3.1.10 make it abstract.
     * <p> As of 4.0.0 add default.
     *
     * @since 2.8
     */
    @Deprecated(since = "4.1.1")
    default Buffer toBuffer() {
        return cloneAsJsonObject().toBuffer();
    }
}
